development:
  adapter: postgresql
  host: localhost
  database: github_project_stats_dev
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  host: localhost
  database: github_project_stats_test
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  host: localhost
  database: github_project_stats_production
  pool: 5
  timeout: 5000